/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as FishingTripDubaiRouteImport } from './routes/fishing-trip-dubai'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RentAYachtDubaiRouteImport } from './routes/rent-a-yacht-dubai'
import { Route as SeoAuditRouteImport } from './routes/seo-audit'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as YachtBookingDubaiRouteImport } from './routes/yacht-booking-dubai'
import { Route as YachtCharterDubaiRouteImport } from './routes/yacht-charter-dubai'
import { Route as YachtPackagesDubaiRouteImport } from './routes/yacht-packages-dubai'
import { Route as YachtPartyDubaiRouteImport } from './routes/yacht-party-dubai'
import { Route as YachtRentalDubaiRouteImport } from './routes/yacht-rental-dubai'
import { Route as ApiCachePurgeRouteImport } from './routes/api.cache-purge'
import { Route as ApiConfigRouteImport } from './routes/api.config'
import { Route as ApiOverridesRouteImport } from './routes/api.overrides'
import { Route as ApiPasswordRouteImport } from './routes/api.password'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const FishingTripDubaiRoute = FishingTripDubaiRouteImport.update({
  id: '/fishing-trip-dubai',
  path: '/fishing-trip-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RentAYachtDubaiRoute = RentAYachtDubaiRouteImport.update({
  id: '/rent-a-yacht-dubai',
  path: '/rent-a-yacht-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAuditRoute = SeoAuditRouteImport.update({
  id: '/seo-audit',
  path: '/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const YachtBookingDubaiRoute = YachtBookingDubaiRouteImport.update({
  id: '/yacht-booking-dubai',
  path: '/yacht-booking-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const YachtCharterDubaiRoute = YachtCharterDubaiRouteImport.update({
  id: '/yacht-charter-dubai',
  path: '/yacht-charter-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const YachtPackagesDubaiRoute = YachtPackagesDubaiRouteImport.update({
  id: '/yacht-packages-dubai',
  path: '/yacht-packages-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const YachtPartyDubaiRoute = YachtPartyDubaiRouteImport.update({
  id: '/yacht-party-dubai',
  path: '/yacht-party-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const YachtRentalDubaiRoute = YachtRentalDubaiRouteImport.update({
  id: '/yacht-rental-dubai',
  path: '/yacht-rental-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCachePurgeRoute = ApiCachePurgeRouteImport.update({
  id: '/api/cache-purge',
  path: '/api/cache-purge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverridesRoute = ApiOverridesRouteImport.update({
  id: '/api/overrides',
  path: '/api/overrides',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordRoute = ApiPasswordRouteImport.update({
  id: '/api/password',
  path: '/api/password',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/fishing-trip-dubai': typeof FishingTripDubaiRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rent-a-yacht-dubai': typeof RentAYachtDubaiRoute
  '/seo-audit': typeof SeoAuditRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/yacht-booking-dubai': typeof YachtBookingDubaiRoute
  '/yacht-charter-dubai': typeof YachtCharterDubaiRoute
  '/yacht-packages-dubai': typeof YachtPackagesDubaiRoute
  '/yacht-party-dubai': typeof YachtPartyDubaiRoute
  '/yacht-rental-dubai': typeof YachtRentalDubaiRoute
  '/api/cache-purge': typeof ApiCachePurgeRoute
  '/api/config': typeof ApiConfigRoute
  '/api/overrides': typeof ApiOverridesRoute
  '/api/password': typeof ApiPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/fishing-trip-dubai': typeof FishingTripDubaiRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rent-a-yacht-dubai': typeof RentAYachtDubaiRoute
  '/seo-audit': typeof SeoAuditRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/yacht-booking-dubai': typeof YachtBookingDubaiRoute
  '/yacht-charter-dubai': typeof YachtCharterDubaiRoute
  '/yacht-packages-dubai': typeof YachtPackagesDubaiRoute
  '/yacht-party-dubai': typeof YachtPartyDubaiRoute
  '/yacht-rental-dubai': typeof YachtRentalDubaiRoute
  '/api/cache-purge': typeof ApiCachePurgeRoute
  '/api/config': typeof ApiConfigRoute
  '/api/overrides': typeof ApiOverridesRoute
  '/api/password': typeof ApiPasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/contact-us': typeof ContactUsRoute
  '/fishing-trip-dubai': typeof FishingTripDubaiRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rent-a-yacht-dubai': typeof RentAYachtDubaiRoute
  '/seo-audit': typeof SeoAuditRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/yacht-booking-dubai': typeof YachtBookingDubaiRoute
  '/yacht-charter-dubai': typeof YachtCharterDubaiRoute
  '/yacht-packages-dubai': typeof YachtPackagesDubaiRoute
  '/yacht-party-dubai': typeof YachtPartyDubaiRoute
  '/yacht-rental-dubai': typeof YachtRentalDubaiRoute
  '/api/cache-purge': typeof ApiCachePurgeRoute
  '/api/config': typeof ApiConfigRoute
  '/api/overrides': typeof ApiOverridesRoute
  '/api/password': typeof ApiPasswordRoute
  '/blog_/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/blog'
    | '/cancellation-policy'
    | '/contact-us'
    | '/fishing-trip-dubai'
    | '/privacy-policy'
    | '/rent-a-yacht-dubai'
    | '/seo-audit'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/yacht-booking-dubai'
    | '/yacht-charter-dubai'
    | '/yacht-packages-dubai'
    | '/yacht-party-dubai'
    | '/yacht-rental-dubai'
    | '/api/cache-purge'
    | '/api/config'
    | '/api/overrides'
    | '/api/password'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/blog'
    | '/cancellation-policy'
    | '/contact-us'
    | '/fishing-trip-dubai'
    | '/privacy-policy'
    | '/rent-a-yacht-dubai'
    | '/seo-audit'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/yacht-booking-dubai'
    | '/yacht-charter-dubai'
    | '/yacht-packages-dubai'
    | '/yacht-party-dubai'
    | '/yacht-rental-dubai'
    | '/api/cache-purge'
    | '/api/config'
    | '/api/overrides'
    | '/api/password'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/blog'
    | '/cancellation-policy'
    | '/contact-us'
    | '/fishing-trip-dubai'
    | '/privacy-policy'
    | '/rent-a-yacht-dubai'
    | '/seo-audit'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/yacht-booking-dubai'
    | '/yacht-charter-dubai'
    | '/yacht-packages-dubai'
    | '/yacht-party-dubai'
    | '/yacht-rental-dubai'
    | '/api/cache-purge'
    | '/api/config'
    | '/api/overrides'
    | '/api/password'
    | '/blog_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  ContactUsRoute: typeof ContactUsRoute
  FishingTripDubaiRoute: typeof FishingTripDubaiRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RentAYachtDubaiRoute: typeof RentAYachtDubaiRoute
  SeoAuditRoute: typeof SeoAuditRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  YachtBookingDubaiRoute: typeof YachtBookingDubaiRoute
  YachtCharterDubaiRoute: typeof YachtCharterDubaiRoute
  YachtPackagesDubaiRoute: typeof YachtPackagesDubaiRoute
  YachtPartyDubaiRoute: typeof YachtPartyDubaiRoute
  YachtRentalDubaiRoute: typeof YachtRentalDubaiRoute
  ApiCachePurgeRoute: typeof ApiCachePurgeRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiOverridesRoute: typeof ApiOverridesRoute
  ApiPasswordRoute: typeof ApiPasswordRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fishing-trip-dubai': {
      id: '/fishing-trip-dubai'
      path: '/fishing-trip-dubai'
      fullPath: '/fishing-trip-dubai'
      preLoaderRoute: typeof FishingTripDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-a-yacht-dubai': {
      id: '/rent-a-yacht-dubai'
      path: '/rent-a-yacht-dubai'
      fullPath: '/rent-a-yacht-dubai'
      preLoaderRoute: typeof RentAYachtDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-audit': {
      id: '/seo-audit'
      path: '/seo-audit'
      fullPath: '/seo-audit'
      preLoaderRoute: typeof SeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yacht-booking-dubai': {
      id: '/yacht-booking-dubai'
      path: '/yacht-booking-dubai'
      fullPath: '/yacht-booking-dubai'
      preLoaderRoute: typeof YachtBookingDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yacht-charter-dubai': {
      id: '/yacht-charter-dubai'
      path: '/yacht-charter-dubai'
      fullPath: '/yacht-charter-dubai'
      preLoaderRoute: typeof YachtCharterDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yacht-packages-dubai': {
      id: '/yacht-packages-dubai'
      path: '/yacht-packages-dubai'
      fullPath: '/yacht-packages-dubai'
      preLoaderRoute: typeof YachtPackagesDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yacht-party-dubai': {
      id: '/yacht-party-dubai'
      path: '/yacht-party-dubai'
      fullPath: '/yacht-party-dubai'
      preLoaderRoute: typeof YachtPartyDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yacht-rental-dubai': {
      id: '/yacht-rental-dubai'
      path: '/yacht-rental-dubai'
      fullPath: '/yacht-rental-dubai'
      preLoaderRoute: typeof YachtRentalDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache-purge': {
      id: '/api/cache-purge'
      path: '/api/cache-purge'
      fullPath: '/api/cache-purge'
      preLoaderRoute: typeof ApiCachePurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overrides': {
      id: '/api/overrides'
      path: '/api/overrides'
      fullPath: '/api/overrides'
      preLoaderRoute: typeof ApiOverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/password': {
      id: '/api/password'
      path: '/api/password'
      fullPath: '/api/password'
      preLoaderRoute: typeof ApiPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  ContactUsRoute: ContactUsRoute,
  FishingTripDubaiRoute: FishingTripDubaiRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RentAYachtDubaiRoute: RentAYachtDubaiRoute,
  SeoAuditRoute: SeoAuditRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  YachtBookingDubaiRoute: YachtBookingDubaiRoute,
  YachtCharterDubaiRoute: YachtCharterDubaiRoute,
  YachtPackagesDubaiRoute: YachtPackagesDubaiRoute,
  YachtPartyDubaiRoute: YachtPartyDubaiRoute,
  YachtRentalDubaiRoute: YachtRentalDubaiRoute,
  ApiCachePurgeRoute: ApiCachePurgeRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiOverridesRoute: ApiOverridesRoute,
  ApiPasswordRoute: ApiPasswordRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
